/*
    rstanarm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rstanarm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rstanarm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.18.0

#include <stan/model/model_header.hpp>

namespace model_density_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_density");
    reader.add_event(48, 46, "end", "model_density");
    return reader;
}

#include <meta_header.hpp>
 class model_density : public prob_grad {
private:
    int M;
    vector_d x;
    vector_d y;
    double rho;
    double sigma;
    vector_d Mu;
public:
    model_density(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_density(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_density_namespace::model_density";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "M", "int", context__.to_vec());
            M = int(0);
            vals_i__ = context__.vals_i("M");
            pos__ = 0;
            M = vals_i__[pos__++];
            current_statement_begin__ = 3;
            validate_non_negative_index("x", "M", M);
            context__.validate_dims("data initialization", "x", "vector_d", context__.to_vec(M));
            validate_non_negative_index("x", "M", M);
            x = vector_d(static_cast<Eigen::VectorXd::Index>(M));
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_i_vec_lim__ = M;
            for (size_t i_vec__ = 0; i_vec__ < x_i_vec_lim__; ++i_vec__) {
                x[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 4;
            validate_non_negative_index("y", "M", M);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(M));
            validate_non_negative_index("y", "M", M);
            y = vector_d(static_cast<Eigen::VectorXd::Index>(M));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_i_vec_lim__ = M;
            for (size_t i_vec__ = 0; i_vec__ < y_i_vec_lim__; ++i_vec__) {
                y[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "rho", "double", context__.to_vec());
            rho = double(0);
            vals_r__ = context__.vals_r("rho");
            pos__ = 0;
            rho = vals_r__[pos__++];
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "sigma", "double", context__.to_vec());
            sigma = double(0);
            vals_r__ = context__.vals_r("sigma");
            pos__ = 0;
            sigma = vals_r__[pos__++];

            // validate, data variables
            current_statement_begin__ = 2;
            current_statement_begin__ = 3;
            current_statement_begin__ = 4;
            current_statement_begin__ = 5;
            current_statement_begin__ = 6;
            // initialize data variables
            current_statement_begin__ = 10;
            validate_non_negative_index("Mu", "M", M);
            Mu = vector_d(static_cast<Eigen::VectorXd::Index>(M));
            stan::math::fill(Mu,DUMMY_VAR__);
            stan::math::assign(Mu,rep_vector(0,M));


            // validate transformed data
            current_statement_begin__ = 10;

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 14;
            validate_non_negative_index("f", "M", M);
            num_params_r__ += M;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_density() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("f")))
            throw std::runtime_error("variable f missing");
        vals_r__ = context__.vals_r("f");
        pos__ = 0U;
        validate_non_negative_index("f", "M", M);
        context__.validate_dims("initialization", "f", "vector_d", context__.to_vec(M));
        vector_d f(static_cast<Eigen::VectorXd::Index>(M));
        for (int j1__ = 0U; j1__ < M; ++j1__)
            f(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(f);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable f: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  f;
            (void) f;  // dummy to suppress unused var warning
            if (jacobian__)
                f = in__.vector_constrain(M,lp__);
            else
                f = in__.vector_constrain(M);


            // transformed parameters
            current_statement_begin__ = 18;
            validate_non_negative_index("p", "M", M);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  p(static_cast<Eigen::VectorXd::Index>(M));
            (void) p;  // dummy to suppress unused var warning

            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p,DUMMY_VAR__);
            current_statement_begin__ = 19;
            validate_non_negative_index("Cov", "M", M);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  Cov(static_cast<Eigen::VectorXd::Index>(M),static_cast<Eigen::VectorXd::Index>(M));
            (void) Cov;  // dummy to suppress unused var warning

            stan::math::initialize(Cov, DUMMY_VAR__);
            stan::math::fill(Cov,DUMMY_VAR__);
            current_statement_begin__ = 20;
            local_scalar_t__ log_lik;
            (void) log_lik;  // dummy to suppress unused var warning

            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik,DUMMY_VAR__);


            current_statement_begin__ = 21;
            stan::math::assign(log_lik, 0);
            current_statement_begin__ = 24;
            stan::math::assign(p, softmax(f));
            current_statement_begin__ = 27;
            for (int i = 1; i <= M; ++i) {

                current_statement_begin__ = 28;
                for (int j = 1; j <= M; ++j) {

                    current_statement_begin__ = 29;
                    stan::model::assign(Cov, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                (sigma * stan::math::exp((-(pow((get_base1(x,i,"x",1) - get_base1(x,j,"x",1)),2)) / rho))), 
                                "assigning variable Cov");
                    current_statement_begin__ = 30;
                    if (as_bool(logical_eq(i,j))) {
                        current_statement_begin__ = 30;
                        stan::model::assign(Cov, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                    stan::model::deep_copy((get_base1(Cov,i,j,"Cov",1) + 0.01)), 
                                    "assigning variable Cov");
                    }
                }
            }

            current_statement_begin__ = 36;
            for (int i = 1; i <= M; ++i) {

                current_statement_begin__ = 37;
                stan::math::assign(log_lik, (log_lik + (get_base1(y,i,"y",1) * stan::math::log(get_base1(p,i,"p",1)))));
            }

            // validate transformed parameters
            for (int i0__ = 0; i0__ < M; ++i0__) {
                if (stan::math::is_uninitialized(p(i0__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: p" << '[' << i0__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }
            for (int i0__ = 0; i0__ < M; ++i0__) {
                for (int i1__ = 0; i1__ < M; ++i1__) {
                    if (stan::math::is_uninitialized(Cov(i0__,i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: Cov" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }
            if (stan::math::is_uninitialized(log_lik)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: log_lik";
                throw std::runtime_error(msg__.str());
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 18;
            stan::math::check_simplex(function__,"p",p);
            current_statement_begin__ = 19;
            stan::math::check_cov_matrix(function__,"Cov",Cov);
            current_statement_begin__ = 20;

            // model body

            current_statement_begin__ = 43;
            lp_accum__.add(multi_normal_log<propto__>(f, Mu, Cov));
            current_statement_begin__ = 45;
            lp_accum__.add(log_lik);

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("f");
        names__.push_back("p");
        names__.push_back("Cov");
        names__.push_back("log_lik");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(M);
        dims__.push_back(M);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "model_density_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d f = in__.vector_constrain(M);
            for (int k_0__ = 0; k_0__ < M; ++k_0__) {
            vars__.push_back(f[k_0__]);
            }

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 18;
            validate_non_negative_index("p", "M", M);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  p(static_cast<Eigen::VectorXd::Index>(M));
            (void) p;  // dummy to suppress unused var warning

            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p,DUMMY_VAR__);
            current_statement_begin__ = 19;
            validate_non_negative_index("Cov", "M", M);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  Cov(static_cast<Eigen::VectorXd::Index>(M),static_cast<Eigen::VectorXd::Index>(M));
            (void) Cov;  // dummy to suppress unused var warning

            stan::math::initialize(Cov, DUMMY_VAR__);
            stan::math::fill(Cov,DUMMY_VAR__);
            current_statement_begin__ = 20;
            local_scalar_t__ log_lik;
            (void) log_lik;  // dummy to suppress unused var warning

            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik,DUMMY_VAR__);


            current_statement_begin__ = 21;
            stan::math::assign(log_lik, 0);
            current_statement_begin__ = 24;
            stan::math::assign(p, softmax(f));
            current_statement_begin__ = 27;
            for (int i = 1; i <= M; ++i) {

                current_statement_begin__ = 28;
                for (int j = 1; j <= M; ++j) {

                    current_statement_begin__ = 29;
                    stan::model::assign(Cov, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                (sigma * stan::math::exp((-(pow((get_base1(x,i,"x",1) - get_base1(x,j,"x",1)),2)) / rho))), 
                                "assigning variable Cov");
                    current_statement_begin__ = 30;
                    if (as_bool(logical_eq(i,j))) {
                        current_statement_begin__ = 30;
                        stan::model::assign(Cov, 
                                    stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                    stan::model::deep_copy((get_base1(Cov,i,j,"Cov",1) + 0.01)), 
                                    "assigning variable Cov");
                    }
                }
            }

            current_statement_begin__ = 36;
            for (int i = 1; i <= M; ++i) {

                current_statement_begin__ = 37;
                stan::math::assign(log_lik, (log_lik + (get_base1(y,i,"y",1) * stan::math::log(get_base1(p,i,"p",1)))));
            }

            // validate transformed parameters
            current_statement_begin__ = 18;
            stan::math::check_simplex(function__,"p",p);
            current_statement_begin__ = 19;
            stan::math::check_cov_matrix(function__,"Cov",Cov);
            current_statement_begin__ = 20;

            // write transformed parameters
            if (include_tparams__) {
            for (int k_0__ = 0; k_0__ < M; ++k_0__) {
            vars__.push_back(p[k_0__]);
            }
            for (int k_1__ = 0; k_1__ < M; ++k_1__) {
                for (int k_0__ = 0; k_0__ < M; ++k_0__) {
                vars__.push_back(Cov(k_0__, k_1__));
                }
            }
        vars__.push_back(log_lik);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_density";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= M; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "f" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= M; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_1__ = 1; k_1__ <= M; ++k_1__) {
                for (int k_0__ = 1; k_0__ <= M; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "Cov" << '.' << k_0__ << '.' << k_1__;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik";
            param_names__.push_back(param_name_stream__.str());
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= M; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "f" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            for (int k_0__ = 1; k_0__ <= (M - 1); ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            for (int k_0__ = 1; k_0__ <= (M + ((M * (M - 1)) / 2)); ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "Cov" << '.' << k_0__;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik";
            param_names__.push_back(param_name_stream__.str());
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef model_density_namespace::model_density stan_model;


#endif
